### ISSUE TITLE
[Bug]: Filepicker crashes the app when we are referencing base64 type files in other widgets

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I add a file in filepicker which is large (>2MB) and set the datatype as base64. My app is crashes when I bind the data with a text widget.

### Steps To Reproduce

1. Go to any app
2. Add a filepicker and set the data format to base64
3. Add a text widget and bind it to filepicker.files
4. Add a file in the filepicker greater than 2mb but less than 5mb. (Note 2mb is a guess, can happen for lower values but not very low values)

Sample file used - [generated_2.txt](https://github.com/appsmithorg/appsmith/files/7860844/generated_2.txt)

Loom link -
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/55d141477a4240ccb3adeb4f18971487-00001.gif)](https://www.loom.com/share/55d141477a4240ccb3adeb4f18971487)

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@prsidhu are you looking into this issue? Please update

**Comment by prsidhu** [comment]
@somangshu @dilippitchika This is a slightly different issue from the one mentioned in #10771. Before rendering the text, Interweave attempts to find all urls and emails in the text through regex matching; and this step seems to be causing the non responsive behaviour. I don't exactly know what is causing the delay, yet. However, if you turn on ```disable links``` option for the text widget before binding to the file input, coupled with the changes made in #11812, then it renders normally.

1. Before:
<img width="1680" alt="Screen Shot 2022-03-17 at 2 58 48 PM" src="https://user-images.githubusercontent.com/5424788/158779926-fac307d4-c404-4a9d-8af6-70f320eb0837.png">

2. After:
<img width="1680" alt="Screen Shot 2022-03-17 at 3 04 11 PM" src="https://user-images.githubusercontent.com/5424788/158780288-de585928-4aa1-46f6-b0b4-559865fedbdd.png">

**Comment by somangshu** [comment]
@prsidhu in case we have the change in #11812 can we guarantee that the app wont be unresponsive even if we have enabled links, can you test this in the PR and if successful, lets link this issue there

**Comment by prsidhu** [comment]
@somangshu this doesn't get resolved with the change in 11812. I have to dig deeper into interweave to resolve this one.

**Comment by prsidhu** [comment]
@somangshu @dilippitchika I have doubts about the validity of this use case. 

Sharing a few data points first:

1. The file associated with this ticket (generated_2.txt) is encoded in utf-8 and it works perfectly well if the textwidget type is set to Text.
2. The file included in the comment is encoded in base64 (largebase64.txt). If textWidget is set to type Base64 and this file is upload, then the app goes into an unresponsive state. 
3. If disableLinks is set to true in textWidget and step 2 ^ is repeated. Then the text is rendered appropriately within 6 secs. 
4. base64 encoding usually results in a larger sized file than the original (~1.3 times). In this scenario, generated_2.txt (3.6MB) when converted to base64, yields largebase64.txt (4.8MB)

Doubts:
1. base64 encoding is usually used for transferring images over the network. Why are trying to bind it to text widget?
2. base64 encoding results in a single long sentence of jumbled letters. Checking for links in a 4.8MB sentence is what makes the app unresponsive. And there are definitely no links or emails to be found after the encoding. 

Have I got some thing wrong here? Are there aspects to this use case that I haven't considered?
If we have to go through with this, could we detect the encoding in the textWidget and disableLinks by default (and perhaps show a warning)?



[largebase64.txt](https://github.com/appsmithorg/appsmith/files/8395783/largebase64.txt)

**Comment by somangshu** [comment]
@prsidhu I agree to you analysis here. Though this does not look like a valid use case, maybe keeping the app functioning is still a ball in our court, if a huge text is displayed in the text widget, this problem will still happen. 

I am for the solution you have proposed that is we are able to identify that the text is actually some encoding we disable parsing for links there. 

@dilippitchika let us know if you have some additional context on the use case!

**Comment by dilippitchika** [comment]
Agreed with @somangshu. My concern is the same that we cannot let the app go into an unresponsive state ever. 

> I am for the solution you have proposed that is we are able to identify that the text is actually some encoding we disable parsing for links there.
I am also for this, if this is possible

**Context**
The user didn't face this issue directly. We were triaging and found this issue happening in the text widget.

**Comment by btsgh** [comment]
Tested in Release, and the app is still crashing in the scenario mentioned in the bug. Hence reopening the issue.

**Comment by somangshu** [comment]
@prsidhu can you please look into this?

**Comment by prsidhu** [comment]
@somangshu @btsgh As discussed in the comments, the file type in the bug is not base64. Loading it with file type "text" works.

**Comment by somangshu** [comment]
@prsidhu in case this is a crash with file type as base64, we will still need to identify the solution, we cant let the apps crash, if there is a problem, we need to let the user know, in case you are talking about a blacklisted method, can we restrict it and notify the user about it

**Comment by somangshu** [comment]
@prsidhu are you looking into this issue, This is been lying here for a while now, has become a part of multiple sprints now

**Comment by prsidhu** [comment]
@somangshu @rohitagarwal88 @dilippitchika 

Updated the fix here:

if number of line breaks in text == 0 and text.length > 2000;
then truncate the text and show a validation error. 
and disable html parsing for links.

Please suggest an appropriate error message.

<img width="1543" alt="Screen Shot 2022-06-23 at 10 54 21 PM" src="https://user-images.githubusercontent.com/5424788/175452906-336b3179-686e-428b-949e-df6be8dae824.png">

**Comment by somangshu** [comment]
@prsidhu this was added to the done pipeline, What the next step on this, Have we merged in any related PR.
