### ISSUE TITLE
[Bug]: Unable to send Forget Password and Invite mail even after configuaration of email service

### ISSUE THREAD

**Issue by Somashekar-B** [appsmithorg/appsmith#13976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

#4368 Is similar to My issue but in that they may have not config the Email service but i had config it correctly but not able to send the Invite mail and Forget password mail. It says it is sent but i did not receive any in inbox

### Steps To Reproduce

1. Create an application 
2. Config the email service
3. Signout and try to send the forget password mail

### Version

Hosted on Cloud AWS

**Comment by Nikhil-Nandagopal** [comment]
@hiteshjoshi @ankitakinger @sharat87 is this because of the reply-to issue? This flow still seems very broken

**Comment by sharat87** [comment]
@Somashekar-B, can you share logs from the `logs/backend/backend.log` file in your stacks folder please?

@Nikhil-Nandagopal, sorry, which reply-to issue? Can you provide a pointer or more details please? Also, have we been seeing more errors in this flow? I'm not aware this flow is considered broken.

**Comment by ankitakinger** [comment]
@sharat87 I think @Nikhil-Nandagopal is pointing to [#13853](https://github.com/appsmithorg/appsmith/issues/13853). Let's wait for the logs from @Somashekar-B.

**Comment by sharat87** [comment]
In that case, @Somashekar-B, can you also share your email configuration please, particularly `APPSMITH_REPLY_TO` please? Please remove sensitive information before sharing here. Thank you.

**Comment by Somashekar-B** [comment]
Sorry i have been working on server hosted by the company and i dont have access to it..

**Comment by sharat87** [comment]
@Somashekar-B, I see. Then I'm guessing there's a separate team that deployed Appsmith on this server, right? So, in that case, is the email configuration done using the Admin Settings from the UI? Then can you confirm if the `Send Test Email` button sends the email correctly?

Also, is it possible to get the `docker.env` file from the server and verify the `APPSMITH_REPLY_TO` value please? You don't have to share it, it your infra team isn't comfortable, I want to know if it's empty, or is set to a single valid email address. It's hard to troubleshoot with access to neither the logs nor the configuration. Thank you.

**Comment by Somashekar-B** [comment]
Test Mail its working properly 
APPSMITH_REPLY_TO is set to single valid email address

**Comment by Somashekar-B** [comment]
May be its not only my problem for you is it working properly..?

**Comment by sharat87** [comment]
Thanks for sharing that. If test mail is working correctly, then your email configuration should be working well. Can you check if those other emails are landing in the spam boxes?

Unfortunately, it's hard to tell what could be going wrong without taking a look at the logs.

**Comment by xolyu** [comment]
I have the same problem with Appsmith version 1.7.3, with my installation via Docker Compose.

I can send the test email without any problems, but the invitation email and password reset emails do not work.

Via GUI, I configured the email settings. I have set "From Address" and "Reply-To Address" to the same email address.

When I do a password reset or invite a user, the following is logged, I can't see any error messages:
```
appsmith  | backend stdout |  - Got request to send email to: user@gmail.com with subject: Appsmith Password Reset
...
appsmith  | backend stdout |  - Going to send email for invite user to test2@mydomain.net
appsmith  | backend stdout |  - Got request to send email to: test2@mydomain.net with subject: Invite for Appsmith
```

When I send the test email, the whole mail is logged by `DEBUG`.


Very strange is that in the GUI I have set the value "TLS Protected Connection" to *enabled*, but in the `docker.env` file it says.
```ini
APPSMITH_MAIL_SMTP_TLS_ENABLED=false
```
If I set this value in the file `docker.env` to `true`, restart Appsmith, the GUI shows *disabled* and the fields Username and Password are hidden.


The mail configuration of `docker.env` looks like this:
```ini
# Email server
APPSMITH_MAIL_ENABLED=true
APPSMITH_MAIL_HOST=mailserver.mydomain.net
APPSMITH_MAIL_PORT=587
APPSMITH_MAIL_USERNAME=appsmith@mydomain.net
APPSMITH_MAIL_PASSWORD=my-password
APPSMITH_MAIL_FROM=appsmith@mydomain.net
APPSMITH_REPLY_TO=appsmith@mydomain.net

# Email server feature toggles
# true | false values
APPSMITH_MAIL_SMTP_AUTH=true
APPSMITH_MAIL_SMTP_TLS_ENABLED=false
```

In both cases, if `APPSMITH_MAIL_SMTP_TLS_ENABLED` is set to `true` or `false`, the test email can be sent successfully.

**Comment by ankitakinger** [comment]
Thank you for the detailed explanation @xolyu.
We'll pick this up this week and fix it. Thanks for pointing this out.

**Comment by xolyu** [comment]
Thank you for the quick turnaround @ankitakinger

The problem is not completely fixed by your change.

You are turning the function of the GUI toggle item _"TLS Protected Connection"_ to the `APPSMITH_MAIL_SMTP_TLS_ENABLED` setting, that is correct.

However, there is a second toggle value `APPSMITH_MAIL_SMTP_AUTH` in the config, this one has *no* GUI element (yet).

In the file 'app/client/src/pages/Settings/config/email.ts' for the elements *"SMTP Username"* and *"SMTP Password"* via `isVisible` the visibility is bound to the setting `APPSMITH_MAIL_SMTP_TLS_ENABLED` - but this is wrong. The visibility must be bound to the setting `APPSMITH_MAIL_SMTP_AUTH`. Or not?

**Comment by ankitakinger** [comment]
@xolyu the change you are suggesting around `APPSMITH_MAIL_SMTP_AUTH` will require a discussion with the team. So as of now, I'm going to merge the current change that fixes the main problem. Will pick the suggestion up in a separate issue if at all needed.

**Comment by ankitakinger** [comment]
@xolyu here is the link of the new issue where you can track the other change you suggested.
https://github.com/appsmithorg/appsmith/issues/14798

**Comment by stevenleeg** [comment]
Was there ever a resolution to this one? I'm also experiencing the same issue on a fresh install of appsmith.

**Comment by Nikhil-Nandagopal** [comment]
@stevenleeg yes this was fixed. Are you still facing an issue with SMTP configuration?
