### ISSUE TITLE
[Bug]: Uploading JSON files on file picker causes the UI to freeze and throw unresponsive alert from the browser

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#15275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a canvas has at least a few dozen widgets and the filepicker widget is used to upload medium-sized JSON files (well within the upload limit set on the filepicker), the UI becomes unresponsive and at times browser ends up throwing an alert box to wait or close tab.

### Steps To Reproduce

1. Drop a handful of widgets on the canvas and group a few of them into containers.
2. Download a few apps to your downloads folder 
3.  Drop a filepicker widget and upload a few of the downloaded apps (let's say 3) using the filepicker widget - observe that the UI freeze when files are being uploaded and there's no indication on what is happening to the app. Clicking on the window also causes the browser to display an unresponsive alert box to either wait or kill the application.

![image](https://user-images.githubusercontent.com/79509062/179503650-1381a495-bd8e-444c-9bbf-4cb849df6f07.png)

### Version

Cloud

**Comment by dilippitchika** [comment]
@ramsaptami can you share the app with @ashit-rath? @ashit-rath looks like a perf problem can you triage this?

**Comment by ramsaptami** [comment]
Shared [the app](https://release.app.appsmith.com/app/megamind/theaming-and-js-objects-628bbf17460c5744a0940553/edit#91cuever72) with @ashit-rath

**Comment by dilippitchika** [comment]
@ashit-rath was able to triage the issue @ramsaptami. The reason for this performance bottleneck is because you are binding the data from the filepicker in a text widget. 

The text widget can only handle certain number of line-breaks post which it starts throttling performance and sometimes leads to apps crashing. We fixed this issue already here - https://github.com/appsmithorg/appsmith/issues/10379

We have imposed a limit on the line breaks to be max of 2 lakh after which we remove line breaks. Based on the performance throttle in your app it feels like we have to decrease the limit even more and introduce our JSON Explorer widget #7090 for visualising objects. Parking this for now and will pick up when we have bandwidth.

**Comment by dilippitchika** [comment]
CC @somangshu triaging is done, please check this out. Need you to check if this is something which can be addressed within performance team.

**Comment by dilippitchika** [comment]
@somangshu FYI need some info what can we do here

**Comment by somangshu** [comment]
@dilippitchika no bandwidth on the performance side + this seems like an effort that will be made under #15699

Now we have already shipped a fix before that kinda deals with the same #12964, is this not helping us with the problem? What is still not working?

**Comment by dilippitchika** [comment]
Looks like we have to test this again once. @kamakshibhat-appsmith @chandannkumar can you please test this scenario again and let us know if there are any performance issues?

**Comment by ramsaptami** [comment]
I've updated the [app link](https://release.app.appsmith.com/app/themes-638dab6944af790cb375db93/edit) since it was broken before. You'll can use the new link @kamakshibhat-appsmith @ChandanBalajiBP

**Comment by somangshu** [comment]
@vsvamsi1 @SatishGandham can we close this issue?
