### ISSUE TITLE
[Bug]: "Secondary stale connection error" When Using MySQL Databases

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#17324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Some users that are using MySQL or MariaDB as datasource get often the error "Secondary stale connection error". Restarting the machine/containers fixes the issue, but is inconvenient for the users.

### Steps To Reproduce

https://app.frontapp.com/open/msg_1ea647ik
https://app.frontapp.com/open/msg_1e9wvc5o
https://app.frontapp.com/open/msg_1e3k7yh8

# Workaround
The following two things may help:
(1) Reduce the number of rows being fetched via [pagination](https://docs.appsmith.com/reference/widgets/table#server-side-pagination). It has been reported / noticed that fetching large number of rows can cause this error. 
(2) Restart the API server. 

### Version

Self-Hosted v1.8.4

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_56b4c)

**Comment by rohan-arthur** [comment]
Intercom link in case no front access: https://app.intercom.io/a/apps/y10e7138/inbox/conversation/164629100150051

**Comment by rohan-arthur** [comment]
update: have reached out to the three users to share server side logs to help investigate this, waiting for response.

**Comment by sumitsum** [comment]
We are hoping that the PR raised for the following issue will also address this issue. Once the PR is merged we will keep monitoring for occurrences of this issue. If no such occurrence is found in the future no we can assume that this issue has been addressed for most use cases. https://github.com/appsmithorg/appsmith/issues/17481

**Comment by PaulMcF1987** [comment]
I had his issue happen to me today.
I have 3 apps on appsmith, it only seemed to effect one of the three apps.

**Comment by PaulMcF1987** [comment]
I restarted the container and it seems to be working now

**Comment by Silviovespoli** [comment]
We are also experiencing the same issue. Currently, we have to restart the Appsmith server twice daily. It appears that the underlying issue is with the internal MongoDB server, which is reaching its connection limit. If you require any additional information, please let us know.

**Comment by Nikhil-Nandagopal** [comment]
@rohan-arthur @sumitsum can you please update with a timeline here?

**Comment by vanscurvy** [comment]
I'm also experiencing this.  I can trigger it by performing the same action in an app twice in a row, even immediately after restarting appsmith.  If you would like to take a look let me know.

**Comment by ame-appsmith** [comment]
[Another user](https://app.frontapp.com/open/msg_1l8ffyrw?key=sWso8kidLNPcafufX4nQgA8G4qCWGqeV) is facing this error.

**Comment by sumitsum** [comment]
A fix was pushed recently that may serve as a fix for a large number of use cases. We should monitor the occurrences for versions 1.9.3 onwards.

**Comment by sumitsum** [comment]
@vanscurvy can you please mention which Appsmith version you are on ? Also, are you using cloud version or self hosted ?

**Comment by vanscurvy** [comment]
Hi @sumitsum - I am self hosted, currently on version  v1.9.3.1

**Comment by hemantkrmmt** [comment]
Hi @sumitsum I have the latest version (Appsmith Community v1.9.3.1) and still getting this issue. It is working fine if we are working on a single table but when I am joining more than one, then Its causing issue.
 
<img width="729" alt="Screenshot 2023-01-18 at 11 28 55 AM" src="https://user-images.githubusercontent.com/13727864/213096004-dcff990c-3286-4362-8788-cb95dbab9e83.png">

**Comment by sumitsum** [comment]
@vanscurvy @hemantkrmmt can you please share what steps I can take to reproduce this issue - is this something that is consistently reproducible ?

**Comment by hemantkrmmt** [comment]
@sumitsum There is a database connection that is valid since some queries are working fine. So, for the query, I am just adding the query inside the the query input box and click on run command. then I am getting the above error.

**Comment by vanscurvy** [comment]
If it is helpful I can try to reproduce in a slimmed down app and share, but won't have time until later in the week.  I am wondering if this issue (or at least my issue) is related to transaction commits or something similar.  Here is a pattern I have noticed in some cases:

1. I take an action the runs a INSERT and UPDATE statement, followed by a COMMIT statement on success.
2. Action is reported as successful (and I can see the COMMIT came through in the mysql general log).
3. I won't see the inserted record in another client if I try to SELECT it though (i.e. mysqlworkbench).
4. I will try to do step 1 again with a new record, and this time it will error out with the "secondary stale connection" error.  Notably, this is the error I get if the the query is an unprepared statement.  If it is a prepared statement, then the error is "Parameter at position 0 is not set".

I was thinking back about this behavior, and I believe it started about 5 or 6 days ago.  I'm wondering if something in the update triggered it?  Maybe some invalid transaction sequence that I was getting away with before, but won't pass now?

I haven't changed any of the connection parameters between appsmith and mysql (not sure if this is possible).  Here is what mysql logs when appsmith connects:
`SET autocommit=1,transaction_isolation='REPEATABLE-READ',session_track_schema=1,session_track_system_variables='autocommit,transaction_isolation'`

In the above example, here is the relevant JS and mysql:

Action JS:
`{{
add_record.run(
).then(() => {
  commit.run();
  showAlert('Record successfully added.','success');
  lookup_records.run();
  startup.reset();
  resetWidget("TABLE_records",true);
  }
).catch(() => {
  rollback.run();
  showAlert('Record could not be added','error');
  showAlert(add_record.data.toString(),'error');
  }
)
}}`

add_record:
`BEGIN;
INSERT INTO media_notes (note_subject, note, media_acquisition_id, page_citation, poi)
  VALUES ("{{INPUT_subject.text}}", "{{INPUT_note.text}}", {{SELECT_book.selectedOptionValue}}, {{INPUT_page_no.text}}, IF({{SWITCH_poi.isSwitchedOn}}, 1, 0));
	UPDATE media_acquisitions SET last_note_datetime = NOW() WHERE id = {{SELECT_book.selectedOptionValue}};`

commit:
`COMMIT;`

lookup_records:
`SELECT page_citation, note_subject, media_notes.note, poi, media_acquisition_id, media_notes.id, media_acquisition_id, CONCAT(b.title, " (", med.category, ")") as Title
FROM media_notes
LEFT JOIN media_acquisitions ma ON ma.id = media_acquisition_id
LEFT JOIN books b ON b.media_id = ma.media_id
LEFT JOIN categories med ON med.id = ma.media_form_id
ORDER BY media_notes.entry_datetime DESC
;
`
startup JS:
`export default {

	reset: async () => {
		storeValue('allow_clear',false);
		storeValue('allow_delete',false);
		resetWidget('SWITCH_edit');
		resetWidget('INPUT_subject')
		resetWidget('INPUT_note');
		resetWidget('SWITCH_poi');
		resetWidget('INPUT_page_no');
		resetWidget('TABLE_records');
	}
}`

mysql log from step 1:
`2023-01-18T14:35:13.081587Z	   50 Query	BEGIN;
2023-01-18T14:35:13.084153Z	   50 Query	INSERT INTO media_notes (note_subject, note, media_acquisition_id, page_citation, poi)
  VALUES ("rth", "rthtr", 41500312, 78, IF(false, 1, 0));
2023-01-18T14:35:13.092678Z	   50 Query	UPDATE media_acquisitions SET last_note_datetime = NOW() WHERE id = 41500312
2023-01-18T14:35:13.305350Z	   48 Query	SELECT page_citation, note_subject, media_notes.note, poi, media_acquisition_id, media_notes.id, media_acquisition_id, CONCAT(b.title, " (", med.category, ")") as Title
FROM media_notes
LEFT JOIN media_acquisitions ma ON ma.id = media_acquisition_id
LEFT JOIN books b ON b.media_id = ma.media_id
LEFT JOIN categories med ON med.id = ma.media_form_id
ORDER BY media_notes.entry_datetime DESC
2023-01-18T14:35:13.390269Z	   49 Query	COMMIT`

mysql log from step 4:
`2023-01-18T14:36:17.116337Z	   51 Query	BEGIN;
2023-01-18T14:36:17.116600Z	   51 Query	INSERT INTO media_notes (note_subject, note, media_acquisition_id, page_citation, poi)
  VALUES ("jghj", "jtyytj", 41500312, 79, IF(false, 1, 0));
2023-01-18T14:36:21.261739Z	   53 Connect	appsmith@172.17.0.1 on home_db_prod using TCP/IP
2023-01-18T14:36:21.263979Z	   53 Query	SET autocommit=1,transaction_isolation='REPEATABLE-READ',session_track_schema=1,session_track_system_variables='autocommit,transaction_isolation'
2023-01-18T14:36:21.273552Z	   53 Query	BEGIN;
2023-01-18T14:36:21.273909Z	   53 Query	INSERT INTO media_notes (note_subject, note, media_acquisition_id, page_citation, poi)
  VALUES ("jghj", "jtyytj", 41500312, 79, IF(false, 1, 0));
2023-01-18T14:36:21.316123Z	   54 Connect	appsmith@172.17.0.1 on home_db_prod using TCP/IP
2023-01-18T14:36:21.322579Z	   55 Connect	appsmith@172.17.0.1 on home_db_prod using TCP/IP
2023-01-18T14:36:21.328192Z	   54 Query	SET autocommit=1,transaction_isolation='REPEATABLE-READ',session_track_schema=1,session_track_system_variables='autocommit,transaction_isolation'
2023-01-18T14:36:21.332878Z	   55 Query	SET autocommit=1,transaction_isolation='REPEATABLE-READ',session_track_schema=1,session_track_system_variables='autocommit,transaction_isolation'
2023-01-18T14:36:21.337683Z	   56 Connect	appsmith@172.17.0.1 on home_db_prod using TCP/IP
2023-01-18T14:36:21.342363Z	   56 Query	SET autocommit=1,transaction_isolation='REPEATABLE-READ',session_track_schema=1,session_track_system_variables='autocommit,transaction_isolation'
2023-01-18T14:36:21.342383Z	   57 Connect	appsmith@172.17.0.1 on home_db_prod using TCP/IP
2023-01-18T14:36:21.344521Z	   57 Query	SET autocommit=1,transaction_isolation='REPEATABLE-READ',session_track_schema=1,session_track_system_variables='autocommit,transaction_isolation'
2023-01-18T14:36:25.497977Z	   54 Query	ROLLBACK
2023-01-18T14:37:03.303840Z	   55 Query	BEGIN;
2023-01-18T14:37:03.304119Z	   55 Query	INSERT INTO media_notes (note_subject, note, media_acquisition_id, page_citation, poi)
  VALUES ('jghj', 'jtyytj', 41500312, '79', IF('0', 1, 0));
2023-01-18T14:37:07.412919Z	   58 Connect	appsmith@172.17.0.1 on home_db_prod using TCP/IP
2023-01-18T14:37:07.415391Z	   58 Query	SET autocommit=1,transaction_isolation='REPEATABLE-READ',session_track_schema=1,session_track_system_variables='autocommit,transaction_isolation'
2023-01-18T14:37:07.480050Z	   60 Connect	appsmith@172.17.0.1 on home_db_prod using TCP/IP
2023-01-18T14:37:07.483061Z	   62 Connect	appsmith@172.17.0.1 on home_db_prod using TCP/IP
2023-01-18T14:37:07.484824Z	   60 Query	SET autocommit=1,transaction_isolation='REPEATABLE-READ',session_track_schema=1,session_track_system_variables='autocommit,transaction_isolation'
2023-01-18T14:37:07.486086Z	   59 Connect	appsmith@172.17.0.1 on home_db_prod using TCP/IP
2023-01-18T14:37:07.488321Z	   61 Connect	appsmith@172.17.0.1 on home_db_prod using TCP/IP
2023-01-18T14:37:07.489016Z	   62 Query	SET autocommit=1,transaction_isolation='REPEATABLE-READ',session_track_schema=1,session_track_system_variables='autocommit,transaction_isolation'
2023-01-18T14:37:07.490735Z	   59 Query	SET autocommit=1,transaction_isolation='REPEATABLE-READ',session_track_schema=1,session_track_system_variables='autocommit,transaction_isolation'
2023-01-18T14:37:07.492770Z	   61 Query	SET autocommit=1,transaction_isolation='REPEATABLE-READ',session_track_schema=1,session_track_system_variables='autocommit,transaction_isolation'
2023-01-18T14:37:07.679588Z	   58 Query	ROLLBACK`

**Comment by vanscurvy** [comment]
I've narrowed down the steps to reproduce the behavior and have started from scratch with the sakila sample database to rule out an issue with my own database.  When the behavior is reproduced, it hangs up my mysql server in someway that prevents other clients (i.e. mysqlworkbench) from running queries against that same database that was queried by appsmith (other databases on the mysql server are not affected).  I am running mysql in a docker container and restarting the docker container restores the database to a workable condition.

Steps to reproduce:

1. Restart mysql docker container
2. On appsmith, confirm that the following queries can be run multiple times in succession with out issue:
`UPDATE payment SET amount = 50.50 WHERE payment_id = 1;`
`BEGIN; UPDATE payment SET amount = 50.50 WHERE payment_id = 1; COMMIT;`
3. Run a query that is a transaction without a COMMIT at the end. Then run a separate query that is just a COMMIT.
`BEGIN; UPDATE payment SET amount = 50.50 WHERE payment_id = 1;`
`COMMIT;`
4. Try running another query and you will get the "secondary stale" error
`UPDATE payment SET amount = 50.50 WHERE payment_id = 1;`

This is the point at which other clients can no longer run queries against the database (they timeout with disconnections).  I have tried running the same sequence from MYSQLWorkbench without issue.

So it seems that I can no longer run transactions across multiple appsmith queries.  Most of my app actions are structured this way so that javascript logic can determine the composition of each transaction and either commit it or roll it back depending on the success or failure of the functions involved.

**Comment by drtakis85** [comment]
I am experiencing the same error and is just happening in an specific app . 
first query runs,  second query give me error - Secondary stale connection error. 
my apps also were design working of queries based on temporary tables i recently read #20018 as an temporary solution I changed al the queries from create temporary table to create CREATE view but still in this specific app i get the stale connection error

**Comment by yasharma2301** [comment]
Hey, this issue is happening to me too. I get this error for a query as simple as `SELECT * FROM table_name WHERE date_column BETWEEN 'valid date' AND 'valid date';`. As I am using Appsmith cloud I can't use the workaround which is restarting the container as suggested by other users.

**Comment by sumitsum** [comment]
@yasharma2301 in this case you can restart your MySQL DB.

**Comment by sumitsum** [comment]
> @sumitsum - I see your latest comment in #20018 . Sounds like my query structure won't work anymore because of the switch to connection pools. This is fine, and I can restructure accordingly, but just wanted to see if you agree, or if this is some other behavior that should still be looked at.

@vanscurvy in case you intend to use temporary tables across queries then yes unfortunately it won't work with the newer Appsmith versions. This is not recommended but you can also try bunching of multiple MySQL queries in the same Appsmith query in case that is possible (ie. the temporary table is getting created and used in the same Appsmith query) - this should work. Otherwise as you have mentioned we would to need to re-structure the queries so that they don't need to access temporary tables across different Appsmith queries.

**Comment by yasharma2301** [comment]
> @yasharma2301 in this case you can try restarting your MySQL DB.

Hey why would restarting DB help here? The same query is working fine in DBeaver

**Comment by sumitsum** [comment]
@yasharma2301 this was a wild guess - I was thinking about the case where in the DB might have reached its limit of total number of open connections that it can support.

**Comment by sumitsum** [comment]
@yasharma2301 in your case what happens when you try to create a new MySQL datasource after getting the error ? Does this new datasource connection work ?

**Comment by yasharma2301** [comment]
> @yasharma2301 in your case what happens when you try to create a new MySQL datasource after getting the error ? Does this new datasource connection work ?

Hey yes, datasource can be created. I just noted one thing, could you tell me approximately how many rows' export or how many kbs of data can appsmith pull based on SQL query. If the number goes beyond a threshold I think I am getting "Secondary Stale Error".

**Comment by sumitsum** [comment]
@yasharma2301 thanks for sharing this. I am not sure about it. I will have to check on this. IMO, Appsmith should be able to pull up a few tens of MBs of data as far as the server is concerned - but I don't think the client would be able to render this much data without significantly impacting the client side performance. Hence it is generally not recomended to pull up more than say 20 rows at a time. 
Also, can you please share how many queries are running simultaneously on the same MySQL datasource for you ? - just gathering some data for debugging purpose.

**Comment by sribalajig** [comment]
This error has spiked after the week of Jan 9, which is about the time the MySQL driver was upgraded.

**Comment by pchambless** [comment]
I'm getting this error as well, but only for a certain query that I can tell...

**Comment by phangs** [comment]
> @yasharma2301 thanks for sharing this. I am not sure about it. I will have to check on this. IMO, Appsmith should be able to pull up a few tens of MBs of data as far as the server is concerned - but I don't think the client would be able to render this much data without significantly impacting the client side performance. Hence it is generally not recomended to pull up more than say 20 rows at a time. It is generally recommended we use pagination: https://docs.appsmith.com/core-concepts/data-access-and-binding/displaying-data-read/display-data-tables#pagination Also, can you please share how many queries are running simultaneously on the same MySQL datasource for you ? - just gathering some data for debugging purpose.

Hi. I am having this issue as well as of today.  Problem with using pagination is that I am using a query that gets a lot of data, around 50,000 rows. It is first displayed in a table using pagination, but I made a button using the same query (without pagination) to download the same data.  

The download option in the table doesn't work for paginated records. Only the first page of the paginated result is downloaded.  This is the reason I have to create a separate function for downloading data.

Before several appsmith updates, there's no stale connection issue.  I do hope there will be  a fix for this immediately

**Comment by phangs** [comment]
Been checking this issue everyday hoping for a fix...

**Comment by nidhi-nair** [comment]
Hey folks! Sorry about the lull on this issue, it seems to have slipped through the cracks, apologies for that. We have a fix for most of the symptoms that you folks have mentioned on this issue. Please let me know if any of you would be willing to test this out on a deploy preview so we're sure the fix works for you while we proceed with shipping this fix.

**Comment by phangs** [comment]
i'm on self-hosted and I can't connect our database as datasource to cloud because of security reasons, dont't know if if could try the preview but i'd be willing to.

**Comment by btsgh** [comment]
@nidhi-nair is this something that can be tested on DP? If yes, could you do a build deploy preview for a DP?

**Comment by nidhi-nair** [comment]
Please follow through [this link](https://ce-21719.dp.appsmith.com/applications) to get to the DP for this fix. Please be aware that the data created here is localized to just his instance and will be unavailable once this PR gets merged.

**Comment by btsgh** [comment]
Update: The data creation is still in progress for this issue. I am in touch with Piyush for the same. Will test once we are able to update the records of the amount 1M and then try with the join query to reproduce the issue
cc: @nidhi-nair

**Comment by btsgh** [comment]
Tried testing this on DP and here are the observations: 
1. For about 800000 plus records, the join query works sometimes, but the DP crashes everytime.
Note: We have to increase the query time out to about 30,000 milliseconds

2. For about 500000 plus records, the join query works. The DP does not crash, but we observe it to be very slow.

**Comment by btsgh** [comment]
Update: @prapullac tested the above by pulling local branch. The secondary stale connection error still pops up there.

**Comment by nidhi-nair** [comment]
Thanks for you patience with this issue @phangs! We're expecting to promote by the end of the week, or latest by early next week.

**Comment by phangs** [comment]
Our Appsmith has just been updated to Release v1.9.15 yet the Secondary Stale Connection problem still exists. I also do not see it in the updates of bug fixes list.

When will this fix be deployed?

**Comment by nidhi-nair** [comment]
Hey @phangs! This did get shipped out in 1.9.14. Looks like our release notes are not reflecting the fix, let me check if we can edit that. That aside, could you please help with the following details?

1. What is the run duration of your query?
2. How frequently are you still seeing the error?
3. Has the behaviour changed at all since the fix?
4. What amount of data are you expecting in your query?

**Comment by GreenFlux** [comment]
Re-opening this issue, as I'm currently facing the same error with MySQL queries on Appsmith Cloud. I have a query that returns around 1000 rows, and running it more than once tends to trigger the **Secondary stale connection error** state. 

@nidhi-nair , this is on Appsmith Cloud, so I can't access the logs to troubleshoot. I'll try to replicate the error on a local instance.

**Comment by rohan-arthur** [comment]
@sumitsum incidence of this error: https://mixpanel.com/project/2032485/view/178891/app/boards#id=4172284&edited-bookmark=W81gCKQAF9qe

**Comment by sumitsum** [comment]
> 

More info provided here: https://theappsmith.slack.com/archives/C040LHZN03V/p1685977150025949?thread_ts=1685976686.630349&cid=C040LHZN03V

**Comment by sumitsum** [comment]
Re-opening because a [new occurrence](https://theappsmith.slack.com/archives/C040LHZN03V/p1692035286459429) has been reported although the overall occurrence has fallen significantly (> 95 % reduction) due to previous fixes.
