### ISSUE TITLE
[Bug]: Uncommitted changes are seen on existing git apps

### ISSUE THREAD

**Issue by laveena-en** [appsmithorg/appsmith#36067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Uncommitted changes are seen on existing git apps
![image](https://github.com/user-attachments/assets/cee03e93-0de1-405c-9e98-10a63d6a3809)
![image](https://github.com/user-attachments/assets/6d0dc926-3435-4b63-b9d9-50f10cc82d04)

### Steps To Reproduce

1. Visit [ee-4987.dp.appsmith.com](https://ee-4987.dp.appsmith.com/)
2. Open any existing git connected app
3. Notice that there are uncommitted changes seen. However, the same app on release doesn't show any uncommitted changes

Example git app: https://ee-4987.dp.appsmith.com/app/promo-2feb-2/page1-65bc822036e8962e466b0bb6?branch=test_new
Git repo: https://github.com/laveena-en/promo-2Feb

I have branched off from `main` (where the uncommitted changes were seen) to branch `test_new` to check the diff
Diff: https://github.com/laveena-en/promo-2Feb/commit/d032fd0dccb56be74c66efd8e2b4872e171b4083

### Public Sample App

 https://ee-4987.dp.appsmith.com/app/promo-2feb-2/page1-65bc822036e8962e466b0bb6?branch=test_new

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Cloud

**Comment by AnaghHegde** [comment]
@laveena-en We are using this DP - https://ee-4517.dp.appsmith.com/applications. Can you check if this is still valid on this dp? This could probably from release changes also. I have merged the latest release. I don't have an existing git connected app on this dp, hence asking you to reverify the same.

**Comment by laveena-en** [comment]
@AnaghHegde Since [ee-4517.dp.appsmith.com/applications](https://ee-4517.dp.appsmith.com/applications) is a fresh instance, we are using [ee-4987.dp.appsmith.com](https://ee-4987.dp.appsmith.com/) to test for existing apps since it contains a dump of release. I re-checked, and I still see uncommitted changes(this issue is not seen on release). I've invited you to the app/workspace to help further debug

WS name: Promo-2Jan
App: https://ee-4987.dp.appsmith.com/app/promo-2feb-2/page1-65bc822036e8962e466b0bb6?branch=main

**Comment by AnaghHegde** [comment]
Fixed via the PR - https://github.com/appsmithorg/appsmith/pull/36354
